region = "ap-south-1"
availability_zone = "ap-south-1a"
availability_zone1 = "ap-south-1b"
project_name = "my-project"
vpc_cidr = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
environment = "uat"
enable_nat_gateway = true
enable_vpc_peering = false
peer_vpc_id = "vpc-xxxxxx" # Only used if enable_vpc_peering is true
