name: Terraform Manual Destroy

on:
  workflow_dispatch:
    inputs:
      component:
        description: Deployed stack to destroy
        required: true
        type: choice
        options:
          - compute
          - storage
          - networking
      confirm_destroy:
        description: Type DESTROY to continue
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: read

concurrency:
  group: terraform-live-${{ github.repository }}
  cancel-in-progress: false

jobs:
  destroy:
    name: Plan and approve destroy
    if: github.ref == 'refs/heads/master'
    uses: bhowmickkrishnendu/terraform-gha-workflows/.github/workflows/terraform-destroy.yml@b88be7b7a9c3aac35e955838823bc3dd259e7032
    with:
      environment: dev
      component: ${{ inputs.component }}
      root_directory: stacks/${{ inputs.component }}
      aws_region: ap-south-1
      terraform_version: 1.14.2
      tfvars_file: terraform.tfvars
      confirm_destroy: ${{ inputs.confirm_destroy }}
      approval_environment: destroy-${{ inputs.component }}
      role_to_assume: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
