name: Terraform Apply

on:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:

    strategy:
      fail-fast: false

      matrix:
        include:
          - environment: dev
            component: networking
            aws_region: ap-south-1

          # - environment: dev
          #   component: compute
          #   aws_region: ap-south-1

          # - environment: uat
          #   component: networking
          #   aws_region: ap-southeast-2

    uses: bhowmickkrishnendu/terraform-gha-workflows/.github/workflows/terraform-plan.yml@main

    with:
      environment: ${{ matrix.environment }}
      component: ${{ matrix.component }}
      aws_region: ${{ matrix.aws_region }}
      terraform_version: 1.14
      tfvars_file: ${{ matrix.environment }}.tfvars
      role_to_assume: arn:aws:iam::234617061868:role/github-actions-terraform-role

    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

  terraform-apply:
    needs: terraform-plan

    strategy:
      fail-fast: false

      matrix:
        include:
          - environment: dev
            component: networking
            aws_region: ap-south-1

          # - environment: dev
          #   component: compute
          #   aws_region: ap-south-1

          # - environment: uat
          #   component: networking
          #   aws_region: ap-south-1

    uses: bhowmickkrishnendu/terraform-gha-workflows/.github/workflows/terraform-apply.yml@main

    with:
      environment: ${{ matrix.environment }}
      component: ${{ matrix.component }}
      aws_region: ${{ matrix.aws_region }}
      terraform_version: 1.14
      role_to_assume: arn:aws:iam::234617061868:role/github-actions-terraform-role