name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          # - uat
          # - prod

      component:
        description: "Component"
        required: true
        type: choice
        options:
          - networking
          - compute
          - storage
          - ecr
          - eks

      confirm_destroy:
        description: "Type DESTROY to continue"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    uses: bhowmickkrishnendu/terraform-gha-workflows/.github/workflows/terraform-destroy.yml@da38804b4d72091543c26eb51fcda47c8d6e6f87

    with:
      environment: ${{ github.event.inputs.environment }}
      component: ${{ github.event.inputs.component }}
      root_directory: stacks/${{ github.event.inputs.component }}
      aws_region: ap-south-1
      tfvars_file: terraform.tfvars
      confirm_destroy: ${{ github.event.inputs.confirm_destroy }}
      role_to_assume: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
    # secrets:
    #   SYS_PUBKEY: ${{ secrets.SYS_PUBKEY }}
